import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/components/providers/app-providers";
import { AiConsultant } from "@/components/chat/ai-consultant";

const DEFAULT_CONSULTANT_API = "https://ai.crm-iot.com";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Пустой AI_CONSULTANT_CLIENT_ID = виджет выключен (dev, превью, форки).
  const consultantClientId = process.env.AI_CONSULTANT_CLIENT_ID?.trim();
  const consultantApiUrl =
    process.env.AI_CONSULTANT_API_URL?.trim() || DEFAULT_CONSULTANT_API;

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <AppProviders>{children}</AppProviders>
        {consultantClientId && (
          <AiConsultant clientId={consultantClientId} apiUrl={consultantApiUrl} />
        )}
      </body>
    </html>
  );
}
